{
 "title": "Consommation énergie",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  { "title": "Synthèse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Proportion du type d'énergie consommé en moyenne",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"maconso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ENEDIS__ENERGIE_SOUTIRAGE\" or r[\"_measurement\"] == \"GRDF__CONSOMMATION\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")"
    }
   ]
  },
  {
   "title": "Dernière consommation gaz",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"maconso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"GRDF__CONSOMMATION\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")"
    }
   ]
  },
  {
   "title": "Dernière consommation électricité",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"maconso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ENEDIS__ENERGIE_SOUTIRAGE\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")"
    }
   ]
  },
  {
   "title": "Dernière puissance apparente maximale",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"maconso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ENEDIS__PMAX_SOUTIRAGE\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kVA\")"
    }
   ]
  },
  {
   "title": "Dernier volume de gaz consommé",
   "type": "stat",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"maconso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"GRDF__CONSOMMATION\")\n  |> filter(fn: (r) => r[\"_field\"] == \"m3\")"
    }
   ]
  },
  { "title": "Consommation électrique", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Consommation électricité",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"maconso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ENEDIS__ENERGIE_SOUTIRAGE\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")"
    }
   ]
  },
  {
   "title": "Courbe de charge électricité trois derniers jours",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"maconso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ENEDIS__CDC_SOUTIRAGE\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kW\")"
    }
   ]
  },
  { "title": "Consommation gaz", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Consommation gaz",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"maconso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"GRDF__CONSOMMATION\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")"
    }
   ]
  },
  {
   "title": "Volume brut consommé gaz",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "query": "from(bucket: \"maconso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"GRDF__CONSOMMATION\")\n  |> filter(fn: (r) => r[\"_field\"] == \"m3\")"
    }
   ]
  }
 ]
}