# ATTENTION : Changer les mots de passes par défaut avant toute utilisation !

version: "3"
services:
  maconso:
    build: maConso
    depends_on:
      - database
    restart: always
    volumes:
      - ./secrets:/usr/src/app/secrets
    environment:
      - INFLUXDB_URL=http://database:8086
      - INFLUXDB_ORG=maconso
      - INFLUXDB_BUCKET=maconso
    env_file:
    - .maConso.env
    networks:
      - maconso
  database:
    restart: always
    image: influxdb:latest
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    expose:
      - 8086
    ports:
      - "8086:8086"
    networks:
      - maconso
    environment:
    - DOCKER_INFLUXDB_INIT_MODE=setup
    - DOCKER_INFLUXDB_INIT_USERNAME=maconso
    - DOCKER_INFLUXDB_INIT_ORG=maconso
    - DOCKER_INFLUXDB_INIT_BUCKET=maconso
    env_file:
    - .maConso.env
  grafana:
    image: grafana/grafana
    depends_on:
      - database
    ports:
      - "3000:3000"
    networks:
      maconso:
    volumes:
      - ./provisioning:/etc/grafana/provisioning
networks:
  maconso: